;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $89,$3f,$8a,$0b,$01,$89,$3a,$01,$89,$38,$01,$89,$36,$01,$89,$35
	.byte $8a,$0c,$01,$89,$34,$01,$89,$33,$02,$89,$32,$03,$89,$31,$04,$00
